### ISSUE TITLE
crates.io squatting

### ISSUE THREAD

**Issue by sjmackenzie** [ndn-rs/ndn-rs#1]
This project hasn't moved at all and is squatting on crates.io namespace https://crates.io/crates/ndn

Can the author start moving this project forward or release the namespace please.

**Comment by imp** [comment]
@sjmackenzie I am not sure there is such thing as "release of the namespace" on crates.io
It is true that I don't have too much time to work on this crate, but I'll be more than happy to accept PRs.
I may also consider moving the ownership to the other party if they appear to have a substantially more advanced implementation and merging the two won't be practical.

**Comment by sjmackenzie** [comment]
Okay excellent, I'll ping you in a few months. \m/ peace out
